const Map<String, String> coinLogos = {
  'BTC': 'https://cryptologos.cc/logos/bitcoin-btc-logo.png',
  'ETH': 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
  'SOL': 'https://cryptologos.cc/logos/solana-sol-logo.png',
  'ADA': 'https://cryptologos.cc/logos/cardano-ada-logo.png',
  'USDT': 'https://cryptologos.cc/logos/tether-usdt-logo.png',
  'MATIC': 'https://cryptologos.cc/logos/polygon-matic-logo.png',
  'BNB': 'https://cryptologos.cc/logos/bnb-bnb-logo.png',
  'XRP': 'https://cryptologos.cc/logos/xrp-xrp-logo.png',
  'DOGE': 'https://cryptologos.cc/logos/dogecoin-doge-logo.png',
  'DOT': 'https://cryptologos.cc/logos/polkadot-new-dot-logo.png',
  'TRX': 'https://cryptologos.cc/logos/tron-trx-logo.png',
  'LTC': 'https://cryptologos.cc/logos/litecoin-ltc-logo.png',
  'AVAX': 'https://cryptologos.cc/logos/avalanche-avax-logo.png',
  'ATOM': 'https://cryptologos.cc/logos/cosmos-atom-logo.png',
  'NEAR': 'https://cryptologos.cc/logos/near-protocol-near-logo.png',
  'XLM': 'https://cryptologos.cc/logos/stellar-xlm-logo.png',
  'FIL': 'https://cryptologos.cc/logos/filecoin-fil-logo.png',
  'APT': 'https://cryptologos.cc/logos/aptos-apt-logo.png',
  'ICP': 'https://cryptologos.cc/logos/internet-computer-icp-logo.png',
  'ARB': 'https://cryptologos.cc/logos/arbitrum-arb-logo.png',
};
