// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANjqLdzqneWnqQaKwwMe7ZkTxv5pRFcP8',
    appId: '1:38597616745:web:0f45622c2ce42702ffeef8',
    messagingSenderId: '38597616745',
    projectId: 'ecommerce-apps-project',
    authDomain: 'ecommerce-apps-project.firebaseapp.com',
    storageBucket: 'ecommerce-apps-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdWoZETbnjkfeGjoaK-3yB2GWcTBzn0Ls',
    appId: '1:38597616745:android:058ee8ed917a9671ffeef8',
    messagingSenderId: '38597616745',
    projectId: 'ecommerce-apps-project',
    storageBucket: 'ecommerce-apps-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEDSpmBbBhx5KAUs6BdcdwewGtE7nb970',
    appId: '1:38597616745:ios:091de19cc9506786ffeef8',
    messagingSenderId: '38597616745',
    projectId: 'ecommerce-apps-project',
    storageBucket: 'ecommerce-apps-project.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEDSpmBbBhx5KAUs6BdcdwewGtE7nb970',
    appId: '1:38597616745:ios:091de19cc9506786ffeef8',
    messagingSenderId: '38597616745',
    projectId: 'ecommerce-apps-project',
    storageBucket: 'ecommerce-apps-project.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANjqLdzqneWnqQaKwwMe7ZkTxv5pRFcP8',
    appId: '1:38597616745:web:3fd2a04ea5f79341ffeef8',
    messagingSenderId: '38597616745',
    projectId: 'ecommerce-apps-project',
    authDomain: 'ecommerce-apps-project.firebaseapp.com',
    storageBucket: 'ecommerce-apps-project.firebasestorage.app',
  );
}
