// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmYetX1PavwA3CNCVlL-muV8jDzA3uYYs',
    appId: '1:503575450443:web:bb88ad351b01d6d771cece',
    messagingSenderId: '503575450443',
    projectId: 'igeg-vault',
    authDomain: 'igeg-vault.firebaseapp.com',
    storageBucket: 'igeg-vault.firebasestorage.app',
    measurementId: 'G-D2HVZ3H9PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUYmIpyFuhiwWdvtfkWbUvSX_Exdiq5HI',
    appId: '1:503575450443:android:d9baebea5f578d0871cece',
    messagingSenderId: '503575450443',
    projectId: 'igeg-vault',
    storageBucket: 'igeg-vault.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLuPhqGL6etQ8z41A7LEO-n--gOrmyWDI',
    appId: '1:503575450443:ios:584b2c89b7ad483671cece',
    messagingSenderId: '503575450443',
    projectId: 'igeg-vault',
    storageBucket: 'igeg-vault.firebasestorage.app',
    iosBundleId: 'com.example.cryptocloneFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLuPhqGL6etQ8z41A7LEO-n--gOrmyWDI',
    appId: '1:503575450443:ios:584b2c89b7ad483671cece',
    messagingSenderId: '503575450443',
    projectId: 'igeg-vault',
    storageBucket: 'igeg-vault.firebasestorage.app',
    iosBundleId: 'com.example.cryptocloneFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmYetX1PavwA3CNCVlL-muV8jDzA3uYYs',
    appId: '1:503575450443:web:45109424fdba4df071cece',
    messagingSenderId: '503575450443',
    projectId: 'igeg-vault',
    authDomain: 'igeg-vault.firebaseapp.com',
    storageBucket: 'igeg-vault.firebasestorage.app',
    measurementId: 'G-565D6V3DM1',
  );

}